---
# nonk8s
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dell-ansible-objectscale
  description: "Ansible Modules for Dell Objectscale"
  tags:
    - ansible
    - devops
    - automation
    - storage
    - dell
    - infrastructure-as-code
    - objectscale
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: dell/ansible-objectscale
  links:
    - url: 'https://galaxy.ansible.com/dellemc/objectscale'
      title: 'Ansible Galaxy'
      icon: 'web'
    - url: 'https://console.redhat.com/ansible/automation-hub/repo/published/dellemc/objectscale'
      title: 'Automation Hub'
      icon: 'web'
    - url: 'https://github.com/dell/ansible-objectscale/issues'
      title: 'Contact Technical Support'
      icon: 'help'
spec:
  type: service
  lifecycle: production
  owner: user:default/shrinidhi_katte
  visibility: all
