[pytest]
testpaths = tests/unit
addopts =
    --cov=plugins/modules
    --cov=plugins/module_utils/utils.py
    --cov=plugins/module_utils/iam_api.py
    --cov-report=term-missing
    --cov-fail-under=90
