# coding: utf-8

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

__metaclass__ = type


# flake8: noqa

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

__metaclass__ = type


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthenticationApi",
    "NamespaceApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Link",
    "NamespaceServiceCreateNamespaceRequest",
    "NamespaceServiceCreateNamespaceResponse",
    "NamespaceServiceCreateRetentionClassRequest",
    "NamespaceServiceGetNamespaceQuotaResponse",
    "NamespaceServiceGetNamespaceResponse",
    "NamespaceServiceGetNamespacesResponse",
    "NamespaceServiceGetNamespacesResponseNamespaceInner",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClasses",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClassesRetentionClassInner",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributeInner",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerVdc",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerVdcLink",
    "NamespaceServiceGetRetentionClassResponse",
    "NamespaceServiceGetRetentionClassesResponse",
    "NamespaceServiceUpdateNamespaceQuotaRequest",
    "NamespaceServiceUpdateNamespaceRequest",
    "NamespaceServiceUpdateRetentionClassRequest",
]

# import apis into sdk package
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.authentication_api import AuthenticationApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.namespace_api import NamespaceApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api_client import ApiClient
# import ApiClient
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api_response import ApiResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.configuration import Configuration
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiAttributeError
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiException
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiKeyError
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiTypeError
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiValueError
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import OpenApiException
# import models into sdk package
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.link import Link
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_create_namespace_request import (
    NamespaceServiceCreateNamespaceRequest)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_create_namespace_response import (
    NamespaceServiceCreateNamespaceResponse)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_create_retention_class_request import (
    NamespaceServiceCreateRetentionClassRequest)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespace_quota_response import (
    NamespaceServiceGetNamespaceQuotaResponse)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespace_response import (
    NamespaceServiceGetNamespaceResponse)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response import (
    NamespaceServiceGetNamespacesResponse)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner import (
    NamespaceServiceGetNamespacesResponseNamespaceInner)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_retention_classes import (  # noqa: E501; noqa: E501; noqa: E501  # noqa: E501  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClasses)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_retention_classes_retention_class_inner import (  # noqa: E501; noqa: E501; noqa: E501  # noqa: E501  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClassesRetentionClassInner)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_user_mapping_inner import (  # noqa: E501; noqa: E501; noqa: E501  # noqa: E501  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_user_mapping_inner_attribute_inner import (  # noqa: E501; noqa: E501; noqa: E501  # noqa: E501  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributeInner)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_vdc import (  # noqa: E501; noqa: E501; noqa: E501  # noqa: E501  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerVdc)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_vdc_link import (  # noqa: E501; noqa: E501; noqa: E501  # noqa: E501  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerVdcLink)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_retention_class_response import (
    NamespaceServiceGetRetentionClassResponse)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_retention_classes_response import (
    NamespaceServiceGetRetentionClassesResponse)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_update_namespace_quota_request import (
    NamespaceServiceUpdateNamespaceQuotaRequest)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_update_namespace_request import (
    NamespaceServiceUpdateNamespaceRequest)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_update_retention_class_request import (
    NamespaceServiceUpdateRetentionClassRequest)
