# coding: utf-8

# flake8: noqa

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthenticationApi",
    "BucketApi",
    "DataVpoolApi",
    "IamApi",
    "MgmtUserInfoApi",
    "NamespaceApi",
    "ObjectVarrayApi",
    "UserManagementApi",
    "UserSecretKeyApi",
    "ZoneInfoApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BucketServiceAddBucketTagsRequest",
    "BucketServiceCreateBucketRequest",
    "BucketServiceCreateBucketRequestCopyPolicy",
    "BucketServiceCreateBucketRequestMinMaxGovernor",
    "BucketServiceCreateBucketRequestSearchMetadataInner",
    "BucketServiceCreateBucketRequestTagSetInner",
    "BucketServiceCreateBucketResponse",
    "BucketServiceCreateBucketResponseMetaData",
    "BucketServiceDeleteBucketTagsRequest",
    "BucketServiceGetBucketACLResponse",
    "BucketServiceGetBucketDefaultLockConfigurationResponse",
    "BucketServiceGetBucketHeadMetadataResponse",
    "BucketServiceGetBucketInfoResponse",
    "BucketServiceGetBucketLockResponse",
    "BucketServiceGetBucketNotificationConfigResponse",
    "BucketServiceGetBucketQuotaResponse",
    "BucketServiceGetBucketRetentionResponse",
    "BucketServiceGetBucketVersioningResponse",
    "BucketServiceGetBucketsResponse",
    "BucketServiceGetBucketsResponseObjectBucketInner",
    "BucketServiceGetBucketsResponseObjectBucketInnerMinMaxGovernor",
    "BucketServiceGetBucketsResponseObjectBucketInnerSearchMetadata",
    "BucketServiceGetEmptyBucketStatusResponse",
    "BucketServiceGetGroupsResponse",
    "BucketServiceGetGroupsResponseGroupInner",
    "BucketServiceGetPermissionsResponse",
    "BucketServiceGetPermissionsResponsePermissionInner",
    "BucketServiceGetSearchMetaDataResponse",
    "BucketServicePutBucketDefaultLockConfigurationRequest",
    "BucketServicePutBucketDefaultLockConfigurationRequestRule",
    "BucketServicePutBucketDefaultLockConfigurationRequestRuleDefaultRetention",
    "BucketServicePutBucketNotificationConfigRequest",
    "BucketServiceSetAdvancedMetadataSearchTargetRequest",
    "BucketServiceSetBucketACLRequest",
    "BucketServiceSetBucketACLRequestAcl",
    "BucketServiceSetBucketACLRequestAclCustomgroupAclInner",
    "BucketServiceSetBucketACLRequestAclGroupAclInner",
    "BucketServiceSetBucketACLRequestAclUserAclInner",
    "BucketServiceSetBucketAutoCommitPeriodRequest",
    "BucketServiceSetBucketDefaultGroupRequest",
    "BucketServiceSetBucketHeadMetadataRequest",
    "BucketServiceSetBucketHeadMetadataRequestMetadataInner",
    "BucketServiceSetBucketLockRequest",
    "BucketServiceSetBucketRetentionRequest",
    "BucketServiceSetBucketVersioningRequest",
    "BucketServiceTestPolicyEditRequest",
    "BucketServiceTestPolicyRequest",
    "BucketServiceUpdateBucketIsStaleAllowedRequest",
    "BucketServiceUpdateBucketOwnerRequest",
    "BucketServiceUpdateBucketQuotaRequest",
    "BucketServiceUpdateBucketTagsRequest",
    "DataServiceVpoolServiceAddToVpoolRequest",
    "DataServiceVpoolServiceCreateDataServiceVpoolRequest",
    "DataServiceVpoolServiceCreateDataServiceVpoolResponse",
    "DataServiceVpoolServiceGetDataServiceStoreResponse",
    "DataServiceVpoolServiceGetDataServiceVpoolsResponse",
    "DataServiceVpoolServiceGetDataServiceVpoolsResponseDataServiceVpoolInner",
    "DataServiceVpoolServiceGetDataServiceVpoolsResponseDataServiceVpoolInnerVarrayMappingsInner",
    "DataServiceVpoolServicePutDataServiceVpoolRequest",
    "DataServiceVpoolServiceRemoveFromVpoolRequest",
    "IamServiceAddUserToGroupResponse",
    "IamServiceAddUserToGroupResponseResponseMetadata",
    "IamServiceAttachGroupPolicyResponse",
    "IamServiceAttachRolePolicyResponse",
    "IamServiceAttachUserPolicyResponse",
    "IamServiceCreateAccessKeyResponse",
    "IamServiceCreateAccessKeyResponseCreateAccessKeyResult",
    "IamServiceCreateAccessKeyResponseCreateAccessKeyResultAccessKey",
    "IamServiceCreateGroupResponse",
    "IamServiceCreateGroupResponseCreateGroupResult",
    "IamServiceCreateGroupResponseCreateGroupResultGroup",
    "IamServiceCreatePolicyResponse",
    "IamServiceCreatePolicyResponseCreatePolicyResult",
    "IamServiceCreatePolicyResponseCreatePolicyResultPolicy",
    "IamServiceCreatePolicyVersionResponse",
    "IamServiceCreatePolicyVersionResponseCreatePolicyVersionResult",
    "IamServiceCreatePolicyVersionResponseCreatePolicyVersionResultPolicyVersion",
    "IamServiceCreateRoleResponse",
    "IamServiceCreateRoleResponseResult",
    "IamServiceCreateRoleResponseResultRole",
    "IamServiceCreateRoleResponseResultRolePermissionsBoundary",
    "IamServiceCreateUserResponse",
    "IamServiceCreateUserResponseCreateUserResult",
    "IamServiceCreateUserResponseCreateUserResultUser",
    "IamServiceCreateUserResponseCreateUserResultUserPermissionsBoundary",
    "IamServiceDeleteAccessKeyResponse",
    "IamServiceDeleteGroupPolicyResponse",
    "IamServiceDeleteGroupResponse",
    "IamServiceDeletePolicyResponse",
    "IamServiceDeletePolicyVersionResponse",
    "IamServiceDeleteRolePermissionsBoundaryResponse",
    "IamServiceDeleteRolePolicyResponse",
    "IamServiceDeleteRoleResponse",
    "IamServiceDeleteUserPermissionsBoundaryResponse",
    "IamServiceDeleteUserPolicyResponse",
    "IamServiceDeleteUserResponse",
    "IamServiceDetachGroupPolicyResponse",
    "IamServiceDetachRolePolicyResponse",
    "IamServiceDetachUserPolicyResponse",
    "IamServiceGetGroupPolicyResponse",
    "IamServiceGetGroupPolicyResponseGetGroupPolicyResult",
    "IamServiceGetGroupResponse",
    "IamServiceGetGroupResponseGetGroupResult",
    "IamServiceGetGroupResponseGetGroupResultUsersInner",
    "IamServiceGetPolicyResponse",
    "IamServiceGetPolicyResponseGetPolicyResult",
    "IamServiceGetPolicyVersionResponse",
    "IamServiceGetPolicyVersionResponseGetPolicyVersionResult",
    "IamServiceGetRolePolicyResponse",
    "IamServiceGetRolePolicyResponseGetRolePolicyResult",
    "IamServiceGetRoleResponse",
    "IamServiceGetUserPolicyResponse",
    "IamServiceGetUserPolicyResponseGetUserPolicyResult",
    "IamServiceGetUserResponse",
    "IamServiceGetUserResponseGetUserResult",
    "IamServiceGetUserResponseGetUserResultUser",
    "IamServiceGetUserResponseGetUserResultUserPermissionsBoundary",
    "IamServiceGetUserResponseGetUserResultUserTagsInner",
    "IamServiceListAccessKeysResponse",
    "IamServiceListAccessKeysResponseListAccessKeysResult",
    "IamServiceListAccessKeysResponseListAccessKeysResultAccessKeyMetadataInner",
    "IamServiceListAttachedGroupPoliciesResponse",
    "IamServiceListAttachedGroupPoliciesResponseListAttachedGroupPoliciesResult",
    "IamServiceListAttachedRolePoliciesResponse",
    "IamServiceListAttachedRolePoliciesResponseListAttachedRolePoliciesResult",
    "IamServiceListAttachedUserPoliciesResponse",
    "IamServiceListGroupPoliciesResponse",
    "IamServiceListGroupPoliciesResponseListGroupPoliciesResult",
    "IamServiceListGroupsForUserResponse",
    "IamServiceListGroupsForUserResponseListGroupsForUserResult",
    "IamServiceListGroupsForUserResponseListGroupsForUserResultGroupsInner",
    "IamServiceListGroupsResponse",
    "IamServiceListGroupsResponseListGroupsResult",
    "IamServiceListGroupsResponseListGroupsResultGroupsInner",
    "IamServiceListPoliciesResponse",
    "IamServiceListPoliciesResponseListPoliciesResult",
    "IamServiceListPolicyVersionsResponse",
    "IamServiceListPolicyVersionsResponseListPolicyVersionsResult",
    "IamServiceListRolePoliciesResponse",
    "IamServiceListRoleTagsResponse",
    "IamServiceListRoleTagsResponseListRoleTagsResult",
    "IamServiceListRolesResponse",
    "IamServiceListRolesResponseResult",
    "IamServiceListUserPoliciesResponse",
    "IamServiceListUserTagsResponse",
    "IamServiceListUserTagsResponseListUserTagsResult",
    "IamServiceListUsersResponse",
    "IamServiceListUsersResponseListUsersResult",
    "IamServiceListUsersResponseListUsersResultUsersInner",
    "IamServicePutGroupPolicyResponse",
    "IamServicePutRolePermissionsBoundaryResponse",
    "IamServicePutRolePolicyResponse",
    "IamServicePutUserPermissionsBoundaryResponse",
    "IamServicePutUserPolicyResponse",
    "IamServiceRemoveUserFromGroupResponse",
    "IamServiceSetDefaultPolicyVersionResponse",
    "IamServiceUntagRoleTagKeysParameter",
    "IamServiceUntagRoleTagKeysParameterKeysInner",
    "IamServiceUpdateAccessKeyResponse",
    "IamServiceUpdateAssumeRolePolicyResponse",
    "IamServiceUpdateRoleResponse",
    "Link",
    "MgmtUserInfoServiceCreateLocalUserInfoRequest",
    "MgmtUserInfoServiceCreateLocalUserInfoResponse",
    "MgmtUserInfoServiceGetLocalUserInfoResponse",
    "MgmtUserInfoServiceGetLocalUserInfosResponse",
    "MgmtUserInfoServiceGetLocalUserInfosResponseMgmtUserInfoInner",
    "MgmtUserInfoServiceModifyLocalUserInfoRequest",
    "NamespaceServiceCreateNamespaceRequest",
    "NamespaceServiceCreateNamespaceResponse",
    "NamespaceServiceCreateRetentionClassRequest",
    "NamespaceServiceGetNamespaceQuotaResponse",
    "NamespaceServiceGetNamespaceResponse",
    "NamespaceServiceGetNamespacesResponse",
    "NamespaceServiceGetNamespacesResponseNamespaceInner",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClasses",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClassesRetentionClassInner",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner",
    "NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributesInner",
    "NamespaceServiceGetRetentionClassResponse",
    "NamespaceServiceGetRetentionClassesResponse",
    "NamespaceServiceUpdateNamespaceQuotaRequest",
    "NamespaceServiceUpdateNamespaceRequest",
    "NamespaceServiceUpdateRetentionClassRequest",
    "ObjectVarrayServiceCreateVirtualArrayRequest",
    "ObjectVarrayServiceCreateVirtualArrayResponse",
    "ObjectVarrayServiceGetVirtualArrayResponse",
    "ObjectVarrayServiceGetVirtualArraysResponse",
    "ObjectVarrayServiceGetVirtualArraysResponseVarrayInner",
    "ObjectVarrayServiceUpdateVirtualArrayRequest",
    "ObjectVarrayServiceUpdateVirtualArrayResponse",
    "UserManagementServiceAddUserRequest",
    "UserManagementServiceAddUserRequestTagsInner",
    "UserManagementServiceAddUserResponse",
    "UserManagementServiceAddUserResponseLink",
    "UserManagementServiceAddUserTagRequest",
    "UserManagementServiceGetAllUsersResponse",
    "UserManagementServiceGetAllUsersResponseBlobuserInner",
    "UserManagementServiceGetUserInfoResponse",
    "UserManagementServiceGetUserLockWithNamespaceResponse",
    "UserManagementServiceGetUserLockWithoutNamespaceResponse",
    "UserManagementServiceGetUserTagsWithNamespaceResponse",
    "UserManagementServiceGetUsersForNamespaceResponse",
    "UserManagementServiceQueryUsersResponse",
    "UserManagementServiceRemoveUserRequest",
    "UserManagementServiceRemoveUserTagsRequest",
    "UserManagementServiceSetUserLockRequest",
    "UserManagementServiceUpdateUserTagRequest",
    "UserSecretKeyServiceCreateNewKeyForUserRequest",
    "UserSecretKeyServiceCreateNewKeyForUserResponse",
    "UserSecretKeyServiceDeleteKeyForUserRequest",
    "UserSecretKeyServiceGetKeysExistForUserResponse",
    "UserSecretKeyServiceGetKeysForUser1Response",
    "UserSecretKeyServiceGetKeysForUserResponse",
    "UserSecretKeyServiceGetKeysForUserResponseLink",
    "ZoneInfoServiceGetLocalVdcResponse",
    "ZoneInfoServiceGetVdcByIdResponse",
    "ZoneInfoServiceGetVdcByNameResponse",
    "ZoneInfoServiceGetVdcByNameResponseVdc",
    "ZoneInfoServiceGetVdcByNameResponseVdcLink",
    "ZoneInfoServiceInsertVdcInfoRequest",
    "ZoneInfoServiceListAllVdcResponse",
    "ZoneInfoServiceListAllVdcResponseVdcInner",
]

# import apis into sdk package
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.authentication_api import AuthenticationApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.bucket_api import BucketApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.data_vpool_api import DataVpoolApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.iam_api import IamApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.mgmt_user_info_api import MgmtUserInfoApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.namespace_api import NamespaceApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.object_varray_api import ObjectVarrayApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.user_management_api import UserManagementApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.user_secret_key_api import UserSecretKeyApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.zone_info_api import ZoneInfoApi
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api_client import ApiClient
# import ApiClient
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api_response import ApiResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.configuration import Configuration
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiAttributeError
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiException
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiKeyError
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiTypeError
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import ApiValueError
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.exceptions import OpenApiException
# import models into sdk package
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_add_bucket_tags_request import (
    BucketServiceAddBucketTagsRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request import (
    BucketServiceCreateBucketRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_copy_policy import (
    BucketServiceCreateBucketRequestCopyPolicy
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_min_max_governor import (
    BucketServiceCreateBucketRequestMinMaxGovernor
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_search_metadata_inner import (
    BucketServiceCreateBucketRequestSearchMetadataInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_tag_set_inner import (
    BucketServiceCreateBucketRequestTagSetInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_response import (
    BucketServiceCreateBucketResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_response_meta_data import (
    BucketServiceCreateBucketResponseMetaData
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_delete_bucket_tags_request import (
    BucketServiceDeleteBucketTagsRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_acl_response import (
    BucketServiceGetBucketACLResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_default_lock_configuration_response import (  # noqa: E501
    BucketServiceGetBucketDefaultLockConfigurationResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_head_metadata_response import (
    BucketServiceGetBucketHeadMetadataResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_info_response import (
    BucketServiceGetBucketInfoResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_lock_response import (
    BucketServiceGetBucketLockResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_notification_config_response import (
    BucketServiceGetBucketNotificationConfigResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_quota_response import (
    BucketServiceGetBucketQuotaResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_retention_response import (
    BucketServiceGetBucketRetentionResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_bucket_versioning_response import (
    BucketServiceGetBucketVersioningResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_buckets_response import (
    BucketServiceGetBucketsResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_buckets_response_object_bucket_inner import (
    BucketServiceGetBucketsResponseObjectBucketInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_buckets_response_object_bucket_inner_min_max_governor import (  # noqa: E501
    BucketServiceGetBucketsResponseObjectBucketInnerMinMaxGovernor
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_buckets_response_object_bucket_inner_search_metadata import (  # noqa: E501
    BucketServiceGetBucketsResponseObjectBucketInnerSearchMetadata
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_empty_bucket_status_response import (
    BucketServiceGetEmptyBucketStatusResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_groups_response import (
    BucketServiceGetGroupsResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_groups_response_group_inner import (
    BucketServiceGetGroupsResponseGroupInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_permissions_response import (
    BucketServiceGetPermissionsResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_permissions_response_permission_inner import (
    BucketServiceGetPermissionsResponsePermissionInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_search_meta_data_response import (
    BucketServiceGetSearchMetaDataResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_put_bucket_default_lock_configuration_request import (  # noqa: E501
    BucketServicePutBucketDefaultLockConfigurationRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_put_bucket_default_lock_configuration_request_rule import (  # noqa: E501
    BucketServicePutBucketDefaultLockConfigurationRequestRule
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_put_bucket_default_lock_configuration_request_rule_default_retention import (  # noqa: E501
    BucketServicePutBucketDefaultLockConfigurationRequestRuleDefaultRetention
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_put_bucket_notification_config_request import (
    BucketServicePutBucketNotificationConfigRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_advanced_metadata_search_target_request import (
    BucketServiceSetAdvancedMetadataSearchTargetRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_acl_request import (
    BucketServiceSetBucketACLRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_acl_request_acl import (
    BucketServiceSetBucketACLRequestAcl
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_acl_request_acl_customgroup_acl_inner import (  # noqa: E501
    BucketServiceSetBucketACLRequestAclCustomgroupAclInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_acl_request_acl_group_acl_inner import (
    BucketServiceSetBucketACLRequestAclGroupAclInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_acl_request_acl_user_acl_inner import (
    BucketServiceSetBucketACLRequestAclUserAclInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_auto_commit_period_request import (
    BucketServiceSetBucketAutoCommitPeriodRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_default_group_request import (
    BucketServiceSetBucketDefaultGroupRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_head_metadata_request import (
    BucketServiceSetBucketHeadMetadataRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_head_metadata_request_metadata_inner import (  # noqa: E501
    BucketServiceSetBucketHeadMetadataRequestMetadataInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_lock_request import (
    BucketServiceSetBucketLockRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_retention_request import (
    BucketServiceSetBucketRetentionRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_versioning_request import (
    BucketServiceSetBucketVersioningRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_test_policy_edit_request import (
    BucketServiceTestPolicyEditRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_test_policy_request import (
    BucketServiceTestPolicyRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_update_bucket_is_stale_allowed_request import (
    BucketServiceUpdateBucketIsStaleAllowedRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_update_bucket_owner_request import (
    BucketServiceUpdateBucketOwnerRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_update_bucket_quota_request import (
    BucketServiceUpdateBucketQuotaRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_update_bucket_tags_request import (
    BucketServiceUpdateBucketTagsRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_add_to_vpool_request import (
    DataServiceVpoolServiceAddToVpoolRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_create_data_service_vpool_request import (  # noqa: E501
    DataServiceVpoolServiceCreateDataServiceVpoolRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_create_data_service_vpool_response import (  # noqa: E501
    DataServiceVpoolServiceCreateDataServiceVpoolResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_get_data_service_store_response import (
    DataServiceVpoolServiceGetDataServiceStoreResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_get_data_service_vpools_response import (
    DataServiceVpoolServiceGetDataServiceVpoolsResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_get_data_service_vpools_response_data_service_vpool_inner import (  # noqa: E501
    DataServiceVpoolServiceGetDataServiceVpoolsResponseDataServiceVpoolInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_get_data_service_vpools_response_data_service_vpool_inner_varray_mappings_inner import (  # noqa: E501
    DataServiceVpoolServiceGetDataServiceVpoolsResponseDataServiceVpoolInnerVarrayMappingsInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_put_data_service_vpool_request import (
    DataServiceVpoolServicePutDataServiceVpoolRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_remove_from_vpool_request import (
    DataServiceVpoolServiceRemoveFromVpoolRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_add_user_to_group_response import (
    IamServiceAddUserToGroupResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_add_user_to_group_response_response_metadata import (
    IamServiceAddUserToGroupResponseResponseMetadata
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_attach_group_policy_response import (
    IamServiceAttachGroupPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_attach_role_policy_response import (
    IamServiceAttachRolePolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_attach_user_policy_response import (
    IamServiceAttachUserPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_access_key_response import (
    IamServiceCreateAccessKeyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_access_key_response_create_access_key_result import (  # noqa: E501
    IamServiceCreateAccessKeyResponseCreateAccessKeyResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_access_key_response_create_access_key_result_access_key import (  # noqa: E501
    IamServiceCreateAccessKeyResponseCreateAccessKeyResultAccessKey
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_group_response import (
    IamServiceCreateGroupResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_group_response_create_group_result import (
    IamServiceCreateGroupResponseCreateGroupResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_group_response_create_group_result_group import (
    IamServiceCreateGroupResponseCreateGroupResultGroup
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_policy_response import (
    IamServiceCreatePolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_policy_response_create_policy_result import (
    IamServiceCreatePolicyResponseCreatePolicyResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_policy_response_create_policy_result_policy import (  # noqa: E501
    IamServiceCreatePolicyResponseCreatePolicyResultPolicy
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_policy_version_response import (
    IamServiceCreatePolicyVersionResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_policy_version_response_create_policy_version_result import (  # noqa: E501
    IamServiceCreatePolicyVersionResponseCreatePolicyVersionResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_policy_version_response_create_policy_version_result_policy_version import (  # noqa: E501
    IamServiceCreatePolicyVersionResponseCreatePolicyVersionResultPolicyVersion
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_role_response import IamServiceCreateRoleResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_role_response_result import (
    IamServiceCreateRoleResponseResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_role_response_result_role import (
    IamServiceCreateRoleResponseResultRole
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_role_response_result_role_permissions_boundary import (  # noqa: E501
    IamServiceCreateRoleResponseResultRolePermissionsBoundary
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_user_response import IamServiceCreateUserResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_user_response_create_user_result import (
    IamServiceCreateUserResponseCreateUserResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_user_response_create_user_result_user import (
    IamServiceCreateUserResponseCreateUserResultUser
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_create_user_response_create_user_result_user_permissions_boundary import (  # noqa: E501
    IamServiceCreateUserResponseCreateUserResultUserPermissionsBoundary
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_access_key_response import (
    IamServiceDeleteAccessKeyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_group_policy_response import (
    IamServiceDeleteGroupPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_group_response import (
    IamServiceDeleteGroupResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_policy_response import (
    IamServiceDeletePolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_policy_version_response import (
    IamServiceDeletePolicyVersionResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_role_permissions_boundary_response import (
    IamServiceDeleteRolePermissionsBoundaryResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_role_policy_response import (
    IamServiceDeleteRolePolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_role_response import IamServiceDeleteRoleResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_user_permissions_boundary_response import (
    IamServiceDeleteUserPermissionsBoundaryResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_user_policy_response import (
    IamServiceDeleteUserPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_delete_user_response import IamServiceDeleteUserResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_detach_group_policy_response import (
    IamServiceDetachGroupPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_detach_role_policy_response import (
    IamServiceDetachRolePolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_detach_user_policy_response import (
    IamServiceDetachUserPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_group_policy_response import (
    IamServiceGetGroupPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_group_policy_response_get_group_policy_result import (  # noqa: E501
    IamServiceGetGroupPolicyResponseGetGroupPolicyResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_group_response import IamServiceGetGroupResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_group_response_get_group_result import (
    IamServiceGetGroupResponseGetGroupResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_group_response_get_group_result_users_inner import (
    IamServiceGetGroupResponseGetGroupResultUsersInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_policy_response import IamServiceGetPolicyResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_policy_response_get_policy_result import (
    IamServiceGetPolicyResponseGetPolicyResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_policy_version_response import (
    IamServiceGetPolicyVersionResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_policy_version_response_get_policy_version_result import (  # noqa: E501
    IamServiceGetPolicyVersionResponseGetPolicyVersionResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_role_policy_response import (
    IamServiceGetRolePolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_role_policy_response_get_role_policy_result import (
    IamServiceGetRolePolicyResponseGetRolePolicyResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_role_response import IamServiceGetRoleResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_user_policy_response import (
    IamServiceGetUserPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_user_policy_response_get_user_policy_result import (
    IamServiceGetUserPolicyResponseGetUserPolicyResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_user_response import IamServiceGetUserResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_user_response_get_user_result import (
    IamServiceGetUserResponseGetUserResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_user_response_get_user_result_user import (
    IamServiceGetUserResponseGetUserResultUser
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_user_response_get_user_result_user_permissions_boundary import (  # noqa: E501
    IamServiceGetUserResponseGetUserResultUserPermissionsBoundary
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_get_user_response_get_user_result_user_tags_inner import (  # noqa: E501
    IamServiceGetUserResponseGetUserResultUserTagsInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_access_keys_response import (
    IamServiceListAccessKeysResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_access_keys_response_list_access_keys_result import (  # noqa: E501
    IamServiceListAccessKeysResponseListAccessKeysResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_access_keys_response_list_access_keys_result_access_key_metadata_inner import (  # noqa: E501
    IamServiceListAccessKeysResponseListAccessKeysResultAccessKeyMetadataInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_attached_group_policies_response import (
    IamServiceListAttachedGroupPoliciesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_attached_group_policies_response_list_attached_group_policies_result import (  # noqa: E501
    IamServiceListAttachedGroupPoliciesResponseListAttachedGroupPoliciesResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_attached_role_policies_response import (
    IamServiceListAttachedRolePoliciesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_attached_role_policies_response_list_attached_role_policies_result import (  # noqa: E501
    IamServiceListAttachedRolePoliciesResponseListAttachedRolePoliciesResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_attached_user_policies_response import (
    IamServiceListAttachedUserPoliciesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_group_policies_response import (
    IamServiceListGroupPoliciesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_group_policies_response_list_group_policies_result import (  # noqa: E501
    IamServiceListGroupPoliciesResponseListGroupPoliciesResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_groups_for_user_response import (
    IamServiceListGroupsForUserResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_groups_for_user_response_list_groups_for_user_result import (  # noqa: E501
    IamServiceListGroupsForUserResponseListGroupsForUserResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_groups_for_user_response_list_groups_for_user_result_groups_inner import (  # noqa: E501
    IamServiceListGroupsForUserResponseListGroupsForUserResultGroupsInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_groups_response import IamServiceListGroupsResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_groups_response_list_groups_result import (
    IamServiceListGroupsResponseListGroupsResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_groups_response_list_groups_result_groups_inner import (  # noqa: E501
    IamServiceListGroupsResponseListGroupsResultGroupsInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_policies_response import (
    IamServiceListPoliciesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_policies_response_list_policies_result import (
    IamServiceListPoliciesResponseListPoliciesResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_policy_versions_response import (
    IamServiceListPolicyVersionsResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_policy_versions_response_list_policy_versions_result import (  # noqa: E501
    IamServiceListPolicyVersionsResponseListPolicyVersionsResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_role_policies_response import (
    IamServiceListRolePoliciesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_role_tags_response import (
    IamServiceListRoleTagsResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_role_tags_response_list_role_tags_result import (
    IamServiceListRoleTagsResponseListRoleTagsResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_roles_response import IamServiceListRolesResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_roles_response_result import (
    IamServiceListRolesResponseResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_user_policies_response import (
    IamServiceListUserPoliciesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_user_tags_response import (
    IamServiceListUserTagsResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_user_tags_response_list_user_tags_result import (
    IamServiceListUserTagsResponseListUserTagsResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_users_response import IamServiceListUsersResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_users_response_list_users_result import (
    IamServiceListUsersResponseListUsersResult
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_list_users_response_list_users_result_users_inner import (  # noqa: E501
    IamServiceListUsersResponseListUsersResultUsersInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_put_group_policy_response import (
    IamServicePutGroupPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_put_role_permissions_boundary_response import (
    IamServicePutRolePermissionsBoundaryResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_put_role_policy_response import (
    IamServicePutRolePolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_put_user_permissions_boundary_response import (
    IamServicePutUserPermissionsBoundaryResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_put_user_policy_response import (
    IamServicePutUserPolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_remove_user_from_group_response import (
    IamServiceRemoveUserFromGroupResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_set_default_policy_version_response import (
    IamServiceSetDefaultPolicyVersionResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_untag_role_tag_keys_parameter import (
    IamServiceUntagRoleTagKeysParameter
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_untag_role_tag_keys_parameter_keys_inner import (
    IamServiceUntagRoleTagKeysParameterKeysInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_update_access_key_response import (
    IamServiceUpdateAccessKeyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_update_assume_role_policy_response import (
    IamServiceUpdateAssumeRolePolicyResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.iam_service_update_role_response import IamServiceUpdateRoleResponse
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.link import Link
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.mgmt_user_info_service_create_local_user_info_request import (
    MgmtUserInfoServiceCreateLocalUserInfoRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.mgmt_user_info_service_create_local_user_info_response import (
    MgmtUserInfoServiceCreateLocalUserInfoResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.mgmt_user_info_service_get_local_user_info_response import (
    MgmtUserInfoServiceGetLocalUserInfoResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.mgmt_user_info_service_get_local_user_infos_response import (
    MgmtUserInfoServiceGetLocalUserInfosResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.mgmt_user_info_service_get_local_user_infos_response_mgmt_user_info_inner import (  # noqa: E501
    MgmtUserInfoServiceGetLocalUserInfosResponseMgmtUserInfoInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.mgmt_user_info_service_modify_local_user_info_request import (
    MgmtUserInfoServiceModifyLocalUserInfoRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_create_namespace_request import (
    NamespaceServiceCreateNamespaceRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_create_namespace_response import (
    NamespaceServiceCreateNamespaceResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_create_retention_class_request import (
    NamespaceServiceCreateRetentionClassRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespace_quota_response import (
    NamespaceServiceGetNamespaceQuotaResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespace_response import (
    NamespaceServiceGetNamespaceResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response import (
    NamespaceServiceGetNamespacesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner import (
    NamespaceServiceGetNamespacesResponseNamespaceInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_retention_classes import (  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClasses
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_retention_classes_retention_class_inner import (  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClassesRetentionClassInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_user_mapping_inner import (  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_user_mapping_inner_attributes_inner import (  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributesInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_retention_class_response import (
    NamespaceServiceGetRetentionClassResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_retention_classes_response import (
    NamespaceServiceGetRetentionClassesResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_update_namespace_quota_request import (
    NamespaceServiceUpdateNamespaceQuotaRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_update_namespace_request import (
    NamespaceServiceUpdateNamespaceRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_update_retention_class_request import (
    NamespaceServiceUpdateRetentionClassRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.object_varray_service_create_virtual_array_request import (
    ObjectVarrayServiceCreateVirtualArrayRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.object_varray_service_create_virtual_array_response import (
    ObjectVarrayServiceCreateVirtualArrayResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.object_varray_service_get_virtual_array_response import (
    ObjectVarrayServiceGetVirtualArrayResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.object_varray_service_get_virtual_arrays_response import (
    ObjectVarrayServiceGetVirtualArraysResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.object_varray_service_get_virtual_arrays_response_varray_inner import (  # noqa: E501
    ObjectVarrayServiceGetVirtualArraysResponseVarrayInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.object_varray_service_update_virtual_array_request import (
    ObjectVarrayServiceUpdateVirtualArrayRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.object_varray_service_update_virtual_array_response import (
    ObjectVarrayServiceUpdateVirtualArrayResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_add_user_request import (
    UserManagementServiceAddUserRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_add_user_request_tags_inner import (
    UserManagementServiceAddUserRequestTagsInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_add_user_response import (
    UserManagementServiceAddUserResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_add_user_response_link import (
    UserManagementServiceAddUserResponseLink
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_add_user_tag_request import (
    UserManagementServiceAddUserTagRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_get_all_users_response import (
    UserManagementServiceGetAllUsersResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_get_all_users_response_blobuser_inner import (  # noqa: E501
    UserManagementServiceGetAllUsersResponseBlobuserInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_get_user_info_response import (
    UserManagementServiceGetUserInfoResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_get_user_lock_with_namespace_response import (  # noqa: E501
    UserManagementServiceGetUserLockWithNamespaceResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_get_user_lock_without_namespace_response import (  # noqa: E501
    UserManagementServiceGetUserLockWithoutNamespaceResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_get_user_tags_with_namespace_response import (  # noqa: E501
    UserManagementServiceGetUserTagsWithNamespaceResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_get_users_for_namespace_response import (
    UserManagementServiceGetUsersForNamespaceResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_query_users_response import (
    UserManagementServiceQueryUsersResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_remove_user_request import (
    UserManagementServiceRemoveUserRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_remove_user_tags_request import (
    UserManagementServiceRemoveUserTagsRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_set_user_lock_request import (
    UserManagementServiceSetUserLockRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_management_service_update_user_tag_request import (
    UserManagementServiceUpdateUserTagRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_secret_key_service_create_new_key_for_user_request import (
    UserSecretKeyServiceCreateNewKeyForUserRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_secret_key_service_create_new_key_for_user_response import (
    UserSecretKeyServiceCreateNewKeyForUserResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_secret_key_service_delete_key_for_user_request import (
    UserSecretKeyServiceDeleteKeyForUserRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_secret_key_service_get_keys_exist_for_user_response import (
    UserSecretKeyServiceGetKeysExistForUserResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_secret_key_service_get_keys_for_user1_response import (
    UserSecretKeyServiceGetKeysForUser1Response
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_secret_key_service_get_keys_for_user_response import (
    UserSecretKeyServiceGetKeysForUserResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_secret_key_service_get_keys_for_user_response_link import (
    UserSecretKeyServiceGetKeysForUserResponseLink
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_get_local_vdc_response import (
    ZoneInfoServiceGetLocalVdcResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_get_vdc_by_id_response import (
    ZoneInfoServiceGetVdcByIdResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_get_vdc_by_name_response import (
    ZoneInfoServiceGetVdcByNameResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_get_vdc_by_name_response_vdc import (
    ZoneInfoServiceGetVdcByNameResponseVdc
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_get_vdc_by_name_response_vdc_link import (
    ZoneInfoServiceGetVdcByNameResponseVdcLink
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_insert_vdc_info_request import (
    ZoneInfoServiceInsertVdcInfoRequest
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_list_all_vdc_response import (
    ZoneInfoServiceListAllVdcResponse
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_list_all_vdc_response_vdc_inner import (
    ZoneInfoServiceListAllVdcResponseVdcInner
)
