"""Stubs for third-party packages used by the generated client.

This module is auto-generated by fix_sanity.py.  It allows the package
to be imported in environments where pydantic / urllib3 / dateutil are
not installed (e.g. ansible-test sanity --test import).
"""
from __future__ import (absolute_import, division, print_function)
# pylint: disable=invalid-name
__metaclass__ = type
# pylint: disable=unused-import,too-few-public-methods

from typing import Any, Dict, Generic, TypeVar

_T = TypeVar('_T')


# --- pydantic stubs ---


class BaseModel(Generic[_T]):
    """Stub BaseModel that stores keyword arguments as attributes.

    When pydantic is not installed this stub provides just enough
    behaviour for the generated OpenAPI models to work:
    * ``__init__(**kw)`` stores every keyword as an instance attribute.
    * ``to_dict()`` / ``model_dump()`` return those attributes as a dict.
    * ``from_dict(d)`` / ``model_validate(d)`` construct an instance from
      a dict, mapping JSON keys to Python attribute names via the class-
      level ``model_fields`` (extracted from ``Field(alias=...)``).
    """

    model_config: dict = {}

    def __init_subclass__(cls, **kw: Any) -> None:
        pass

    def __init__(self, **kw: Any) -> None:
        for key, val in kw.items():
            object.__setattr__(self, key, val)

    # -- serialisation helpers ------------------------------------------------

    def to_dict(self, **kw: Any) -> dict:
        return {
            k: _stub_serialise(v)
            for k, v in self.__dict__.items()
            if v is not None
        }

    def model_dump(self, **kw: Any) -> dict:
        return {
            k: _stub_serialise(v)
            for k, v in self.__dict__.items()
            if v is not None
        }

    def to_json(self) -> str:
        import json as _json
        return _json.dumps(self.to_dict())

    # -- deserialisation helpers ----------------------------------------------

    @classmethod
    def _alias_map(cls) -> Dict[str, str]:
        """Build ``{json_alias: python_attr}`` from class annotations + Field defaults."""
        mapping: Dict[str, str] = {}
        annotations = {}
        for klass in reversed(cls.__mro__):
            annotations.update(getattr(klass, '__annotations__', {}))
        for attr_name in annotations:
            field_default = cls.__dict__.get(attr_name)
            if isinstance(field_default, _FieldInfo) and field_default.alias:
                mapping[field_default.alias] = attr_name
            else:
                mapping[attr_name] = attr_name
        return mapping

    @classmethod
    def from_dict(cls, obj: Any) -> Any:
        if obj is None:
            return None
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, j: str) -> Any:
        import json as _json
        return cls.from_dict(_json.loads(j))

    @classmethod
    def model_validate(cls, obj: Any, **kw: Any) -> Any:
        if obj is None:
            return None
        if not isinstance(obj, dict):
            return cls()
        alias_map = cls._alias_map()
        mapped: Dict[str, Any] = {}
        for key, val in obj.items():
            attr = alias_map.get(key, key)
            mapped[attr] = val
        return cls(**mapped)


def _stub_serialise(val: Any) -> Any:
    """Recursively serialise values produced by stub models."""
    if val is None:
        return None
    if isinstance(val, BaseModel):
        return val.to_dict()
    if isinstance(val, list):
        return [_stub_serialise(v) for v in val]
    if isinstance(val, dict):
        return {k: _stub_serialise(v) for k, v in val.items()}
    return val


class _FieldInfo:
    """Tiny holder so ``Field(alias=...)`` works in stub mode."""

    def __init__(self, default: Any = None, alias: Any = None, **kw: Any) -> None:
        self.default = default
        self.alias = alias


def ConfigDict(**kw: Any) -> Any:
    """Stub ConfigDict."""
    return {}


def Field(*a: Any, **kw: Any) -> Any:
    """Stub Field – returns a _FieldInfo so alias mapping works."""
    return _FieldInfo(default=kw.get('default'), alias=kw.get('alias'))


def validate_call(*a: Any, **kw: Any) -> Any:
    """Stub validate_call."""
    def decorator(fn: Any) -> Any:
        return fn
    if a and callable(a[0]):
        return a[0]
    return decorator


StrictStr = str
StrictInt = int
StrictFloat = float
StrictBool = bool


# --- typing_extensions stubs for Python 3.8 compatibility ---


class NotRequired:
    """Stub NotRequired for Python 3.8 compatibility."""

    def __class_getitem__(cls, item: Any) -> Any:
        return item


class Annotated:
    """Stub Annotated for Python 3.8 compatibility."""

    def __class_getitem__(cls, item: Any) -> Any:
        if isinstance(item, tuple) and item:
            return item[0]
        return item


class Literal:
    """Stub Literal for Python 3.7 compatibility."""

    def __class_getitem__(cls, item: Any) -> Any:
        return item


class ClassVar:
    """Stub ClassVar for Python 3.7 compatibility."""

    def __class_getitem__(cls, item: Any) -> Any:
        return item


# Create a base class for TypedDict inheritance
_TypedDictBase = dict


class TypedDictMeta(type):
    """Metaclass for TypedDict to support both function and class usage."""

    def __call__(cls, name: str = None, fields: Dict[str, Any] = None, total: bool = True, **kw: Any):
        """Support both TypedDict(name, fields) and TypedDict() for inheritance."""
        if name is not None and fields is not None:
            # Function call: TypedDict(name, fields)
            return type(name, (_TypedDictBase,), fields)
        else:
            # Class instantiation for inheritance
            return super().__call__()


class TypedDict(_TypedDictBase, metaclass=TypedDictMeta):
    """Stub TypedDict for Python 3.7 compatibility."""
    pass


Self = Any


StrictBytes = bytes


class SecretStr(str):
    """Stub SecretStr that behaves like str but provides get_secret_value()."""

    def get_secret_value(self) -> str:
        return str(self)


# --- urllib3 stubs ---


class _Util:
    """Stub urllib3.util."""

    @staticmethod
    def make_headers(**kw: Any) -> dict:
        return {}


class _Urllib3:
    """Stub urllib3 module."""

    HTTPResponse = object
    PoolManager = object
    ProxyManager = object
    util = _Util()

    class exceptions:  # pylint: disable=invalid-name
        """Stub urllib3.exceptions."""
        InsecureRequestWarning = type(
            "InsecureRequestWarning", (Warning,), {}
        )

    @staticmethod
    def disable_warnings(*a: Any, **kw: Any) -> None:
        pass


urllib3_stub = _Urllib3()


# --- dateutil stubs ---


class _DateutilParser:
    """Stub dateutil.parser."""

    @staticmethod
    def parse(s: str, **kw: Any) -> Any:
        return s


dateutil_parser_stub = _DateutilParser()
