"""Stubs for third-party packages used by the generated client.

This module is auto-generated by fix_sanity.py.  It allows the package
to be imported in environments where pydantic / urllib3 / dateutil are
not installed (e.g. ansible-test sanity --test import).
"""
from __future__ import (absolute_import, division, print_function)
# pylint: disable=invalid-name
__metaclass__ = type
# pylint: disable=unused-import,too-few-public-methods

from typing import Any, Dict, Generic, TypeVar

_T = TypeVar('_T')


# --- pydantic stubs ---


class BaseModel(Generic[_T]):
    """Stub BaseModel for import compatibility."""

    model_config: dict = {}

    def __init_subclass__(cls, **kw: Any) -> None:
        pass

    def __init__(self, **kw: Any) -> None:
        pass

    def to_dict(self) -> dict:
        return {}

    def to_json(self) -> str:
        return "{}"

    @classmethod
    def from_dict(cls, obj: Any) -> Any:
        return cls()

    @classmethod
    def from_json(cls, j: str) -> Any:
        return cls()

    @classmethod
    def model_validate(cls, obj: Any, **kw: Any) -> Any:
        return cls()


def ConfigDict(**kw: Any) -> Any:
    """Stub ConfigDict."""
    return {}


def Field(*a: Any, **kw: Any) -> Any:
    """Stub Field."""
    return None  # type: ignore


def validate_call(*a: Any, **kw: Any) -> Any:
    """Stub validate_call."""
    def decorator(fn: Any) -> Any:
        return fn
    if a and callable(a[0]):
        return a[0]
    return decorator


StrictStr = str
StrictInt = int
StrictFloat = float
StrictBool = bool


# --- typing_extensions stubs for Python 3.8 compatibility ---


class NotRequired:
    """Stub NotRequired for Python 3.8 compatibility."""

    def __class_getitem__(cls, item: Any) -> Any:
        return item


class Annotated:
    """Stub Annotated for Python 3.8 compatibility."""

    def __class_getitem__(cls, item: Any) -> Any:
        if isinstance(item, tuple) and item:
            return item[0]
        return item


class Literal:
    """Stub Literal for Python 3.7 compatibility."""

    def __class_getitem__(cls, item: Any) -> Any:
        return item


class ClassVar:
    """Stub ClassVar for Python 3.7 compatibility."""

    def __class_getitem__(cls, item: Any) -> Any:
        return item


# Create a base class for TypedDict inheritance
_TypedDictBase = dict


class TypedDictMeta(type):
    """Metaclass for TypedDict to support both function and class usage."""

    def __call__(cls, name: str = None, fields: Dict[str, Any] = None, total: bool = True, **kw: Any):
        """Support both TypedDict(name, fields) and TypedDict() for inheritance."""
        if name is not None and fields is not None:
            # Function call: TypedDict(name, fields)
            return type(name, (_TypedDictBase,), fields)
        else:
            # Class instantiation for inheritance
            return super().__call__()


class TypedDict(_TypedDictBase, metaclass=TypedDictMeta):
    """Stub TypedDict for Python 3.7 compatibility."""
    pass


Self = Any


StrictBytes = bytes
SecretStr = str


# --- urllib3 stubs ---


class _Util:
    """Stub urllib3.util."""

    @staticmethod
    def make_headers(**kw: Any) -> dict:
        return {}


class _Urllib3:
    """Stub urllib3 module."""

    HTTPResponse = object
    PoolManager = object
    ProxyManager = object
    util = _Util()

    class exceptions:  # pylint: disable=invalid-name
        """Stub urllib3.exceptions."""
        InsecureRequestWarning = type(
            "InsecureRequestWarning", (Warning,), {}
        )

    @staticmethod
    def disable_warnings(*a: Any, **kw: Any) -> None:
        pass


urllib3_stub = _Urllib3()


# --- dateutil stubs ---


class _DateutilParser:
    """Stub dateutil.parser."""

    @staticmethod
    def parse(s: str, **kw: Any) -> Any:
        return s


dateutil_parser_stub = _DateutilParser()
