"""API response object.

NOTE: Initially generated by OpenAPI Generator.
This module is now manually maintained in this collection.
Generation automation must not overwrite or auto-format this file.
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

__metaclass__ = type

from typing import Generic, Mapping, Optional, TypeVar

try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub  # type: ignore
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub  # type: ignore
try:
    from pydantic import StrictBytes
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBytes  # stub  # type: ignore
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub  # type: ignore

T = TypeVar("T")


class ApiResponse(BaseModel, Generic[T]):  # type: ignore[reportGeneralTypeIssues]  # type: ignore[reportGeneralTypeIssues]  # type: ignore[reportGeneralTypeIssues]  # type: ignore[reportGeneralTypeIssues]  # noqa: E501
    """
    API response object
    """

    status_code: StrictInt = Field(description="HTTP status code")
    headers: Optional[Mapping[str, str]] = Field(None, description="HTTP headers")
    data: T = Field(description="Deserialized data given the data type")
    raw_data: StrictBytes = Field(description="Raw data (HTTP response body)")

    model_config = {
        "arbitrary_types_allowed": True
    }
