# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, List, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_tag_set_inner import (
    BucketServiceCreateBucketRequestTagSetInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_buckets_response_object_bucket_inner_min_max_governor import (  # noqa: E501
    BucketServiceGetBucketsResponseObjectBucketInnerMinMaxGovernor
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_get_buckets_response_object_bucket_inner_search_metadata import (  # noqa: E501
    BucketServiceGetBucketsResponseObjectBucketInnerSearchMetadata
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.link import Link
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class BucketServiceGetBucketsResponseObjectBucketInner(BaseModel):
    """BucketServiceGetBucketsResponseObjectBucketInner"""
    name: Optional[StrictStr] = Field(
        default=None,
        description="Name assigned to this resource in ECS. The resource name is set by  a user and can be changed at any time. It is not a unique identifier.")
    id: Optional[StrictStr] = Field(
        default=None,
        description="Identifier that is generated by ECS when the resource is created.  The resource Id is guaranteed to be unique  and  immutable across all  virtual data centers for all time.")  # noqa: E501
    link: Optional[Link] = None
    created: Optional[StrictStr] = Field(default=None, description="Bucket creation time")
    softquota: Optional[StrictStr] = Field(default=None, description="Bucket soft quota")
    fs_access_enabled: Optional[StrictBool] = Field(default=None, description="Bucket \"file system access enabled\" status")
    locked: Optional[StrictBool] = Field(default=None, description="\"Locked\" status of a bucket")
    vpool: Optional[StrictStr] = Field(default=None, description="Replication group id")
    namespace: Optional[StrictStr] = Field(default=None, description="Namespace")
    owner: Optional[StrictStr] = Field(default=None, description="Bucket owner")
    is_stale_allowed: Optional[StrictBool] = Field(default=None, description="Bucket isStaleAllowed flag")
    is_object_lock_with_ado_allowed: Optional[StrictBool] = Field(
        default=None, description="If true Object Lock and ADO can be enabled together.  See the Admin Guide for more information.")
    is_tso_read_only: Optional[StrictBool] = Field(default=None, description="Bucket isStaleAllowed flag")
    is_object_lock_enabled: Optional[StrictBool] = Field(default=None, description="Bucket isObjectLockEnabled flag")
    default_object_lock_retention_mode: Optional[StrictStr] = Field(default=None, description="Default object lock retention mode")
    default_object_lock_retention_years: Optional[StrictInt] = Field(default=None, description="Default object lock retention years")
    default_object_lock_retention_days: Optional[StrictInt] = Field(default=None, description="Default object lock retention days")
    is_encryption_enabled: Optional[StrictStr] = Field(default=None, description="D@RE  Bucket isEncryptionEnabled flag")
    default_retention: Optional[StrictInt] = Field(default=None, description="Default bucket retention")
    block_size: Optional[StrictInt] = Field(default=None, description="Block size in GB")
    auto_commit_period: Optional[StrictInt] = Field(default=None, description="auto-commit interval")
    notification_size: Optional[StrictInt] = Field(default=None, description="Notification size in GB")
    api_type: Optional[StrictStr] = Field(default=None, description="API type")
    tag_set: Optional[List[BucketServiceCreateBucketRequestTagSetInner]] = Field(
        default=None, description="Keywords and labels that can be added by a user to a resource  to make it easy to find when doing a search.", alias="TagSet")
    retention: Optional[StrictInt] = Field(default=None, description="Default retention value for the bucket.")
    default_group_file_read_permission: Optional[StrictBool] = Field(default=None, description="Flag indicating the Read permission for default group")
    default_group_file_write_permission: Optional[StrictBool] = Field(default=None, description="Flag indicating the file write permission for default group")
    default_group_file_execute_permission: Optional[StrictBool] = Field(
        default=None, description="Flag indicating the file execute permission for default group")
    default_group_dir_read_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory read permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group_dir_write_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory write permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group_dir_execute_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory execute permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group: Optional[StrictStr] = Field(default=None, description="Bucket's default group")
    search_metadata: Optional[BucketServiceGetBucketsResponseObjectBucketInnerSearchMetadata] = None
    min_max_governor: Optional[BucketServiceGetBucketsResponseObjectBucketInnerMinMaxGovernor] = None
    audit_delete_expiration: Optional[StrictInt] = Field(default=None, description="Bucket audit delete expiration in seconds")
    is_empty_bucket_in_progress: Optional[StrictBool] = Field(
        default=None,
        description="Optional.  If true the bucket is in the process of being deleted.  The bucket will be read only and no changes will be allowed on the bucket   until the operation completes.")  # noqa: E501
    block_size_in_count: Optional[StrictInt] = Field(default=None, alias="blockSizeInCount")
    notification_size_in_count: Optional[StrictInt] = Field(default=None, alias="notificationSizeInCount")
    enable_advanced_metadata_search: Optional[StrictBool] = Field(default=None, alias="enableAdvancedMetadataSearch")
    advanced_metadata_search_target_name: Optional[StrictStr] = Field(default=None, alias="advancedMetadataSearchTargetName")
    advanced_metadata_search_target_stream: Optional[StrictStr] = Field(default=None, alias="advancedMetadataSearchTargetStream")
    local_object_metadata_reads: Optional[StrictBool] = Field(default=None, description="Local object metadata reads bucket flag.")
    versioning_status: Optional[StrictStr] = Field(default=None, description="Bucket versioning status.")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
