# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, List, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_acl_request_acl_customgroup_acl_inner import (  # noqa: E501
    BucketServiceSetBucketACLRequestAclCustomgroupAclInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_acl_request_acl_group_acl_inner import (
    BucketServiceSetBucketACLRequestAclGroupAclInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_set_bucket_acl_request_acl_user_acl_inner import (
    BucketServiceSetBucketACLRequestAclUserAclInner
)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class BucketServiceSetBucketACLRequestAcl(BaseModel):
    """Get ACL for the bucket"""
    owner: Optional[StrictStr] = Field(default=None, description="Owner name")
    default_group: Optional[StrictStr] = Field(default=None, description="Default group")
    user_acl: Optional[List[BucketServiceSetBucketACLRequestAclUserAclInner]] = None
    group_acl: Optional[List[BucketServiceSetBucketACLRequestAclGroupAclInner]] = Field(default=None, description="List of Acl group")
    customgroup_acl: Optional[List[BucketServiceSetBucketACLRequestAclCustomgroupAclInner]] = Field(default=None, description="List of custom group Acls")
    default_group_file_perms: Optional[List[StrictStr]] = Field(default=None, description="The default group's file permissions")
    default_group_dir_perms: Optional[List[StrictStr]] = Field(default=None, description="The default group's directory permissions")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
