# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, Optional, Union

try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictFloat
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictFloat  # stub
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class BucketServiceGetEmptyBucketStatusResponse(BaseModel):
    """BucketServiceGetEmptyBucketStatusResponse"""
    status: Optional[StrictStr] = Field(default=None, description="Overall status of the bucket delete task   Valid values: PENDING, IN_PROGRESS, POST_PROCESSING, DONE, FAILED, ABORT_IN_PROGRESS, ABORTED   <br>   PENDING - The task has been created and will start execution once it is successfully configured.   <br>   IN_PROGRESS - The task is executing normally.   <br>   POST_PROCESSING - The task is finsished processing and is finalizing before moving to the DONE or FAILED state.   <br>   DONE - The task successfully completed and the bucket was deleted.   <br>   ABORT_IN_PROGRESS - The tasks is aborting and is finalizing before moving to the ABORTED state.   <br>   ABORTED - The task was stopped before it could complete and should be retried.   <br>   FAILED - The task completed but not all items associated with the bucket could be removed.   <br>   <br>   When the status is FAILED the failed_to_delete_n counts give an indication of why certain items could not be removed by the task.")  # noqa: E501
    created: Optional[StrictInt] = Field(default=None, description="Date when the task was created")
    last_updated: Optional[StrictInt] = Field(default=None, description="Date when the task was last updated")
    entries_deleted: Optional[StrictInt] = Field(default=None, description="Total Number of items deleted since the task was started")
    failed_to_delete_due_to_retention: Optional[StrictInt] = Field(default=None, description="Number of items under retention that could not be deleted")
    failed_to_delete_due_to_other: Optional[StrictInt] = Field(
        default=None, description="Number of items that could not be removed because of issues other than retention, permission, or dangling")
    approx_object_count: Optional[StrictInt] = None
    approx_total_size: Optional[Union[StrictFloat, StrictInt]] = None
    approx_total_size_unit_string: Optional[StrictStr] = None
    message: Optional[StrictStr] = Field(default=None, description="Optional status message")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
