# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, List, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_copy_policy import (
    BucketServiceCreateBucketRequestCopyPolicy
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_min_max_governor import (
    BucketServiceCreateBucketRequestMinMaxGovernor
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_search_metadata_inner import (
    BucketServiceCreateBucketRequestSearchMetadataInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.bucket_service_create_bucket_request_tag_set_inner import (
    BucketServiceCreateBucketRequestTagSetInner
)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class BucketServiceCreateBucketRequest(BaseModel):
    """BucketServiceCreateBucketRequest"""
    block_size: Optional[StrictInt] = Field(
        default=None,
        description="Block size in GB. Cannot be less than 1GB or use decimal values.  Can be set to -1 to indicate quota value not defined.",
        alias="blockSize")
    notification_size: Optional[StrictInt] = Field(
        default=None,
        description="Notification size in GB. Cannot be less than 1GB or use decimal values.  Can be set to -1 to indicate quota value not defined.",
        alias="notificationSize")
    name: StrictStr = Field(description="Bucket name")
    vpool: Optional[StrictStr] = Field(default=None, description="Replication group identifier")
    filesystem_enabled: Optional[StrictBool] = Field(default=None, description="flag indicating whether file-system is enabled for this bucket")
    head_type: Optional[StrictStr] = Field(
        default=None,
        description="HeadType indicates the object head type that is allowed to access the bucket. If the bucket has FS-Enabled,  then the FS heads are implicitly allowed to access this bucket")  # noqa: E501
    namespace: Optional[StrictStr] = Field(default=None, description="Namespace associated with the user/tenant that is allowed to access the bucket")
    tag_set: Optional[List[BucketServiceCreateBucketRequestTagSetInner]] = Field(
        default=None, description="Tags - list of tags set for the Bucket", alias="TagSet")
    is_encryption_enabled: Optional[StrictBool] = Field(default=None, description="tag to enable encryption for the bucket")
    default_group_file_read_permission: Optional[StrictBool] = Field(default=None, description="Flag indicating the Read permission for default group")
    default_group_file_write_permission: Optional[StrictBool] = Field(default=None, description="Flag indicating the file write permission for default group")
    default_group_file_execute_permission: Optional[StrictBool] = Field(
        default=None, description="Flag indicating the file execute permission for default group")
    default_group_dir_read_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory read permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group_dir_write_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory write permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group_dir_execute_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory execute permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group: Optional[StrictStr] = Field(default=None, description="Default group for Filesystem-enabled buckets")
    autocommit_period: Optional[StrictInt] = Field(default=None, description="Default autocommit period in seconds")
    retention: Optional[StrictInt] = Field(default=None, description="Default retention period in seconds")
    is_stale_allowed: Optional[StrictBool] = Field(default=None, description="tag to allow stale data in bucket")
    is_object_lock_with_ado_allowed: Optional[StrictBool] = Field(
        default=None, description="permanently sets flag on the bucket to allow Object Lock and ADO to be enabled together.")
    is_tso_read_only: Optional[StrictBool] = Field(default=None, description="enable the Access During Outage option, which allows read access")
    search_metadata: Optional[List[BucketServiceCreateBucketRequestSearchMetadataInner]] = Field(
        default=None, description="Searchable tags assigned to objects created within the bucket.")
    metadata_tokens: Optional[StrictBool] = Field(
        default=None, description="metadata search: whether to treat metadata value as array of values (true) or single value (false)")
    owner: Optional[StrictStr] = Field(default=None, description="Bucket owner")
    min_max_governor: Optional[BucketServiceCreateBucketRequestMinMaxGovernor] = None
    audited_delete_expiration: Optional[StrictInt] = Field(default=None, description="Audit delete expiration time in seconds")
    is_object_lock_enabled: Optional[StrictBool] = Field(default=None, description="Enables object lock for existing bucket.")
    storage_policy: Optional[StrictStr] = None
    block_size_in_count: Optional[StrictInt] = Field(default=None, alias="blockSizeInCount")
    notification_size_in_count: Optional[StrictInt] = Field(default=None, alias="notificationSizeInCount")
    copy_policy: Optional[BucketServiceCreateBucketRequestCopyPolicy] = None
    enable_advanced_metadata_search: Optional[StrictBool] = Field(default=None, alias="enableAdvancedMetadataSearch")
    advanced_metadata_search_target_name: Optional[StrictStr] = Field(default=None, alias="advancedMetadataSearchTargetName")
    advanced_metadata_search_target_stream: Optional[StrictStr] = Field(default=None, alias="advancedMetadataSearchTargetStream")
    local_object_metadata_reads: Optional[StrictBool] = Field(default=None, description="Local object metadata reads bucket flag.")
    versioning_status: Optional[StrictStr] = Field(default=None, description="versioning status for the bucket")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
