# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, Optional

try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class BucketServiceSetBucketDefaultGroupRequest(BaseModel):
    """BucketServiceSetBucketDefaultGroupRequest"""
    default_group_file_read_permission: Optional[StrictBool] = Field(default=None, description="Flag indicating the Read permission for default group")
    default_group_file_write_permission: Optional[StrictBool] = Field(default=None, description="Flag indicating the file write permission for default group")
    default_group_file_execute_permission: Optional[StrictBool] = Field(
        default=None, description="Flag indicating the file execute permission for default group")
    default_group_dir_read_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory read permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group_dir_write_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory write permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group_dir_execute_permission: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating the directory execute permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects")  # noqa: E501
    default_group: Optional[StrictStr] = Field(default=None, description="Default group for Filesystem-enabled buckets")
    namespace: Optional[StrictStr] = Field(default=None, description="Namespace for bucket")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
