# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, List, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_get_data_service_vpools_response_data_service_vpool_inner import (  # noqa: E501
    DataServiceVpoolServiceGetDataServiceVpoolsResponseDataServiceVpoolInner
)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class DataServiceVpoolServiceGetDataServiceVpoolsResponse(BaseModel):
    """DataServiceVpoolServiceGetDataServiceVpoolsResponse"""
    data_service_vpool: List[DataServiceVpoolServiceGetDataServiceVpoolsResponseDataServiceVpoolInner] = Field(description="A list of dataservice vpools")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
