# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, List, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.data_service_vpool_service_get_data_service_vpools_response_data_service_vpool_inner_varray_mappings_inner import (  # noqa: E501
    DataServiceVpoolServiceGetDataServiceVpoolsResponseDataServiceVpoolInnerVarrayMappingsInner
)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class DataServiceVpoolServiceCreateDataServiceVpoolRequest(BaseModel):
    """DataServiceVpoolServiceCreateDataServiceVpoolRequest"""
    id: StrictStr = Field(description="Identifier for this replication group")
    name: StrictStr = Field(description="Unique name identifying this classification of replication group")
    description: Optional[StrictStr] = Field(default=None, description="Description of this replication group")
    zone_mappings: Optional[List[DataServiceVpoolServiceGetDataServiceVpoolsResponseDataServiceVpoolInnerVarrayMappingsInner]] = Field(
        default=None, description="List of varrayId-zoneId tuples with are associated with the same vpool created under data-services")
    enable_rebalancing: Optional[StrictBool] = Field(default=None, description="set if geo rebalancing is enabled")
    is_allow_all_namespaces: Optional[StrictBool] = Field(
        default=None,
        description="set if Vpool Allows access to all Namespaces for dataservices",
        alias="isAllowAllNamespaces")
    is_full_rep: Optional[StrictBool] = Field(default=None, description="set full replication flag", alias="isFullRep")
    use_replication_target: Optional[StrictBool] = None

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
