# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, List, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner import (
    NamespaceServiceGetNamespacesResponseNamespaceInner)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub  # type: ignore
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub  # type: ignore
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub  # type: ignore
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub  # type: ignore
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub  # type: ignore


class NamespaceServiceGetNamespacesResponse(BaseModel):  # type: ignore[reportGeneralTypeIssues]
    """NamespaceServiceGetNamespacesResponse"""
    namespace: Optional[List[NamespaceServiceGetNamespacesResponseNamespaceInner]] = Field(default=None, description="A list of namespaces")
    max_namespaces: Optional[StrictInt] = Field(default=None, description="Number of Namespaces requested.", alias="MaxNamespaces")
    next_marker: Optional[StrictStr] = Field(default=None, description="Reference object to retrieve next set of objects.", alias="NextMarker")
    filter: Optional[StrictStr] = Field(default=None, description="filter used to get the objects.", alias="Filter")
    next_page_link: Optional[StrictStr] = Field(default=None, description="link to get the next page.", alias="NextPageLink")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional["NamespaceServiceGetNamespacesResponse"]:
        if obj is None:
            return None
        return cls.model_validate(obj)
