# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, Optional

try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub  # type: ignore
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub  # type: ignore
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub  # type: ignore
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub  # type: ignore
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub  # type: ignore


class NamespaceServiceGetNamespaceQuotaResponse(BaseModel):  # type: ignore[reportGeneralTypeIssues]
    """NamespaceServiceGetNamespaceQuotaResponse"""
    namespace: Optional[StrictStr] = Field(default=None, description="Gets Namespace")
    block_size: Optional[StrictInt] = Field(default=None, description="Block size in GB.", alias="blockSize")
    notification_size: Optional[StrictInt] = Field(default=None, description="Notification size in GB.", alias="notificationSize")
    block_size_in_count: Optional[StrictInt] = Field(default=None, description="Block size in count.", alias="blockSizeInCount")
    notification_size_in_count: Optional[StrictInt] = Field(default=None, description="Notification size in count.", alias="notificationSizeInCount")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional["NamespaceServiceGetNamespaceQuotaResponse"]:
        if obj is None:
            return None
        return cls.model_validate(obj)

