# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, List, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.link import Link
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_retention_classes import (  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClasses
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_user_mapping_inner import (  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner
)
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_get_vdc_by_name_response_vdc import (
    ZoneInfoServiceGetVdcByNameResponseVdc
)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class NamespaceServiceGetNamespacesResponseNamespaceInner(BaseModel):
    """NamespaceServiceGetNamespacesResponseNamespaceInner"""
    default_data_services_vpool: Optional[StrictStr] = Field(default=None,
                                                             description="Default replication group identifier for this tenant when creating buckets")
    allowed_vpools_list: Optional[List[StrictStr]] = Field(default=None, description="List of replication group that are allowed access to namespace")
    disallowed_vpools_list: List[StrictStr] = Field(description="List of replication group that are not allowed access to namespace")
    namespace_admins: Optional[StrictStr] = Field(default=None, description="Comma separated list of namespace admins")
    is_encryption_enabled: Optional[StrictStr] = Field(default=None, description="encryption status of the namesapce")
    user_mapping: Optional[List[NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner]
                           ] = Field(default=None, description="List of user mappings for this tenant")
    default_bucket_block_size: Optional[StrictInt] = Field(default=None, description="Default bucket quota size.")
    external_group_admins: Optional[StrictStr] = Field(default=None, description="List of groups from AD Server")
    is_stale_allowed: Optional[StrictBool] = Field(default=None, description="Namespace isStaleAllowed flag")
    is_object_lock_with_ado_allowed: Optional[StrictBool] = Field(default=None, description="Optional  <br>  Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Existing buckets are not affected by this flag.  <br>  When true the is_object_lock_with_ado_allowed flag is applied to new buckets allowing them to enable  Object Lock with ADO without having to explicitly enable the flag on the bucket.  <br>  When false or omitted, buckets created in the namespace will not be allowed to enable OBJECT LOCK with writable ADO unless  the is_object_lock_with_ado_allowed flag is explicitly enabled on the bucket.  <br>  The flag only affects new buckets.  Existing buckets must set the flag explicitly to allow Object Lock with ADO.  <br>  Warning: Once the flag is enabled on a bucket it cannot be changed. Make sure you understand the risk of data loss before enabling this flag. See the Admin Guide for more information.")  # noqa: E501
    is_compliance_enabled: Optional[StrictBool] = Field(default=None, description="Namespace isComplianceEnabled flag")
    notification_size: Optional[StrictInt] = Field(default=None, description="Notification Size in GB.", alias="notificationSize")
    block_size: Optional[StrictInt] = Field(default=None, description="Blocksize in GB", alias="blockSize")
    notification_size_in_count: Optional[StrictInt] = Field(default=None, description="Notification Size in Count.", alias="notificationSizeInCount")
    block_size_in_count: Optional[StrictInt] = Field(default=None, description="Blocksize in Count", alias="blockSizeInCount")
    retention_classes: Optional[NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClasses] = None
    default_audit_delete_expiration: Optional[StrictInt] = Field(default=None, description="Default bucket audit delete expiration")
    root_user_name: Optional[StrictStr] = None
    root_user_password: Optional[StrictStr] = None
    name: Optional[StrictStr] = Field(
        default=None,
        description="Name assigned to this resource in ECS. The resource name is set by  a user and can be changed at any time. It is not a unique identifier.")
    id: Optional[StrictStr] = Field(
        default=None,
        description="Identifier that is generated by ECS when the resource is created.  The resource Id is guaranteed to be unique  and  immutable across all  virtual data centers for all time.")  # noqa: E501
    link: Optional[Link] = None
    creation_time: Optional[StrictInt] = Field(default=None, description="Timestamp that shows when this resource was created in ECS")
    inactive: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the resource is inactive. When a user removes  a resource, the resource is put in this state before  it is removed from the ECS database.")  # noqa: E501
    var_global: Optional[StrictBool] = Field(default=None, description="Indicates whether the resource is global.", alias="global")
    remote: Optional[StrictBool] = Field(default=None, description="Indicates whether the resource is remote.")
    vdc: Optional[ZoneInfoServiceGetVdcByNameResponseVdc] = None
    internal: Optional[StrictBool] = Field(default=None, description="Indicated whether the resource is an internal resource")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
