# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, List, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.namespace_service_get_namespaces_response_namespace_inner_user_mapping_inner import (  # noqa: E501
    NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner
)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub  # type: ignore
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub  # type: ignore
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub  # type: ignore
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub  # type: ignore
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub  # type: ignore
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub  # type: ignore


class NamespaceServiceCreateNamespaceRequest(BaseModel):  # type: ignore[reportGeneralTypeIssues]
    """NamespaceServiceCreateNamespaceRequest"""
    namespace: StrictStr = Field(description="User provided namespace (verified unique)  <p>can not include dots or slashes (.|/) in the name</p>")
    default_object_project: Optional[StrictStr] = Field(default=None, description="Default project id for this tenant when creating buckets")
    default_data_services_vpool: Optional[StrictStr] = Field(default=None,
                                                             description="Default replication group identifier for this tenant when creating buckets")
    allowed_vpools_list: Optional[List[StrictStr]] = Field(
        default=None, description="List of replication groups that are allowed to create buckets on the corresponding namespace")
    disallowed_vpools_list: Optional[List[StrictStr]] = Field(
        default=None, description="List of replication groups that are not allowed to create buckets on the corresponding namespace")
    namespace_admins: Optional[StrictStr] = Field(default=None, description="Comma separated list of namespace admins")
    user_mapping: Optional[List[NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner]] = Field(default=None, description="List of user mappings")
    is_encryption_enabled: Optional[StrictBool] = Field(default=None, description="tag to enable encryption for the namespace")
    default_bucket_block_size: Optional[StrictInt] = Field(default=None, description="Default bucket quota size.")
    external_group_admins: Optional[StrictStr] = Field(default=None, description="List of groups from AD Server")
    is_stale_allowed: Optional[StrictBool] = Field(default=None, description="Tag to allow stale data within the namespace")
    is_object_lock_with_ado_allowed: Optional[StrictBool] = Field(default=None, description="Optional  <br>  Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Existing buckets are not affected by this flag.  <br>  When true the is_object_lock_with_ado_allowed flag is applied to new buckets allowing them to enable  Object Lock with ADO without having to explicitly enable the flag on the bucket.  <br>  When false or omitted, buckets created in the namespace will not be allowed to enable OBJECT LOCK with writable ADO unless  the is_object_lock_with_ado_allowed flag is explicitly enabled on the bucket.  <br>  The flag only affects new buckets.  Existing buckets must set the flag explicitly to allow Object Lock with ADO.  <br>  Warning: Once the flag is enabled on a bucket it cannot be changed. Make sure you understand the risk of data loss before enabling this flag. See the Admin Guide for more information.")  # noqa: E501
    compliance_enabled: Optional[StrictBool] = Field(default=None, description="Tag to enable namespace compliance")
    default_audit_delete_expiration: Optional[StrictInt] = Field(default=None, description="default bucket audit delete expiration")
    root_user_password: Optional[StrictStr] = Field(default=None, description="password for namespace 'virtual root' user")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional["NamespaceServiceCreateNamespaceRequest"]:
        if obj is None:
            return None
        return cls.model_validate(obj)

