# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, Optional

try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class ObjectVarrayServiceUpdateVirtualArrayResponse(BaseModel):
    """ObjectVarrayServiceUpdateVirtualArrayResponse"""
    id: Optional[StrictStr] = Field(default=None, description="Storage pool id")
    name: Optional[StrictStr] = Field(default=None, description="Storage pool name")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    is_cold_storage_enabled: Optional[StrictBool] = Field(
        default=None,
        description="Flag indicating that cold storage encoding is enabled",
        alias="isColdStorageEnabled")
    number_of_data_blocks: Optional[StrictInt] = Field(default=None, description="Number of Data Blocks in EC Scheme", alias="numberOfDataBlocks")
    number_of_code_blocks: Optional[StrictInt] = Field(default=None, description="Number of Code Blocks in EC Scheme", alias="numberOfCodeBlocks")
    warning_alert_at: Optional[StrictInt] = Field(
        default=None,
        description="Threshold percent at which warning alert is raised.  Valid values are from -1 to 100. Value of -1 means do not alert",
        alias="warningAlertAt")
    error_alert_at: Optional[StrictInt] = Field(
        default=None,
        description="Threshold percent at which error alert is raised.  Valid values are from -1 to 100. Value of -1 means do not alert",
        alias="errorAlertAt")
    critical_alert_at: Optional[StrictInt] = Field(
        default=None,
        description="Threshold percent at which critical alert is raised.  Valid values are from -1 to 100. Value of -1 means do not alert",
        alias="criticalAlertAt")
    status: Optional[StrictInt] = Field(default=None, description="flag for status, -1 for null, 0 ~ 6 for value")
    label: Optional[StrictStr] = Field(default=None, description="Drive technology of VArray")
    drive_technology: Optional[StrictStr] = Field(default=None, alias="driveTechnology")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
