# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.user_secret_key_service_get_keys_for_user_response_link import (
    UserSecretKeyServiceGetKeysForUserResponseLink
)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class UserSecretKeyServiceGetKeysExistForUserResponse(BaseModel):
    """UserSecretKeyServiceGetKeysExistForUserResponse"""
    secret_key_1: Optional[StrictStr] = Field(default=None, description="First secret key")
    secret_key_1_exist: Optional[StrictBool] = Field(default=None, description="First secret key exist")
    key_timestamp_1: Optional[StrictStr] = Field(default=None, description="First key creation timestamp in ISO-8601 format")
    key_expiry_timestamp_1: Optional[StrictStr] = Field(default=None, description="First key expiration timestamp in ISO-8601 format")
    secret_key_2: Optional[StrictStr] = Field(default=None, description="Second secret key")
    secret_key_2_exist: Optional[StrictBool] = Field(default=None, description="Second secret key exist")
    key_timestamp_2: Optional[StrictStr] = Field(default=None, description="Second key creation timestamp in ISO-8601 format")
    key_expiry_timestamp_2: Optional[StrictStr] = Field(default=None, description="Second key expiry timestamp in ISO-8601 format")
    link: Optional[UserSecretKeyServiceGetKeysForUserResponseLink] = None
    secret_key_1_id: Optional[StrictStr] = Field(default=None, description="SHA-256 hash for secret key 1")
    secret_key_2_id: Optional[StrictStr] = Field(default=None, description="SHA-256 hash for secret key 2")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
