# coding: utf-8

"""
    Dell ObjectScale/ECS Management API

    Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from typing import Any, Dict, Optional

from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.link import Link
from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.models.zone_info_service_get_vdc_by_name_response_vdc import (
    ZoneInfoServiceGetVdcByNameResponseVdc
)
try:
    from pydantic import BaseModel
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import BaseModel  # stub
try:
    from pydantic import ConfigDict
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import ConfigDict  # stub
try:
    from pydantic import Field
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Field  # stub
try:
    from pydantic import StrictBool
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictBool  # stub
try:
    from pydantic import StrictInt
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictInt  # stub
try:
    from pydantic import StrictStr
except ImportError:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import StrictStr  # stub
try:
    from typing_extensions import Self
except ImportError:
    try:
        from typing import Self  # Python 3.11+
    except ImportError:
        from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client._stubs import Self  # stub


class ZoneInfoServiceGetLocalVdcResponse(BaseModel):
    """ZoneInfoServiceGetLocalVdcResponse"""
    vdc_id: Optional[StrictStr] = Field(default=None, description="VDC id", alias="vdcId")
    vdc_name: Optional[StrictStr] = Field(default=None, description="VDC name", alias="vdcName")
    inter_vdc_end_points: Optional[StrictStr] = Field(default=None, description="VDC end points", alias="interVdcEndPoints")
    inter_vdc_cmd_end_points: Optional[StrictStr] = Field(default=None, description="VDC cmd end points", alias="interVdcCmdEndPoints")
    secret_keys: Optional[StrictStr] = Field(default=None, description="Secret key for this VDC", alias="secretKeys")
    permanently_failed: Optional[StrictBool] = Field(default=None, description="True of vdc is permanently failed, false otherwise.", alias="permanentlyFailed")
    local: Optional[StrictBool] = Field(default=None, description="True of this vdc is local, false otherwise")
    is_encryption_enabled: Optional[StrictBool] = Field(default=None, description="True of this vdc is enabled for encryption, false otherwise")
    management_end_points: Optional[StrictStr] = Field(default=None, description="The management end points for the VDC", alias="managementEndPoints")
    hosted: Optional[StrictBool] = None
    name: Optional[StrictStr] = Field(
        default=None,
        description="Name assigned to this resource in ECS. The resource name is set by  a user and can be changed at any time. It is not a unique identifier.")
    id: Optional[StrictStr] = Field(
        default=None,
        description="Identifier that is generated by ECS when the resource is created.  The resource Id is guaranteed to be unique  and  immutable across all  virtual data centers for all time.")  # noqa: E501
    link: Optional[Link] = None
    creation_time: Optional[StrictInt] = Field(default=None, description="Timestamp that shows when this resource was created in ECS")
    inactive: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the resource is inactive. When a user removes  a resource, the resource is put in this state before  it is removed from the ECS database.")  # noqa: E501
    var_global: Optional[StrictBool] = Field(default=None, description="Indicates whether the resource is global.", alias="global")
    remote: Optional[StrictBool] = Field(default=None, description="Indicates whether the resource is remote.")
    vdc: Optional[ZoneInfoServiceGetVdcByNameResponseVdc] = None
    internal: Optional[StrictBool] = Field(default=None, description="Indicated whether the resource is an internal resource")

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        return cls.model_validate(obj)
