#!/usr/bin/python
# Copyright: (c) 2026, Dell Technologies
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

"""Ansible module for gathering VDC information from Dell ObjectScale"""

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

DOCUMENTATION = r'''
---
module: vdc_info

version_added: '1.0.0'

short_description: Gather VDC (Virtual Data Center) information from Dell ObjectScale

description:
- Gather information about ObjectScale Virtual Data Centers (VDCs).
- Supports listing all VDCs in a single site or across a multi-site federation.
- Supports fetching a specific VDC by name or by ID.
- Supports fetching the local VDC details.
- All operations are non-disruptive read-only queries.
- The C(secretKeys) field is always omitted from output to prevent credential exposure.

author:
- Dell Ansible Team (@dell) <ansible.team@dell.com>

extends_documentation_fragment:
- dellemc.objectscale.objectscale

options:
  vdc_name:
    description:
    - Name of the VDC to retrieve.
    - If specified, returns details of a single VDC matching that name.
    - Mutually exclusive with I(vdc_id) and I(local_vdc).
    type: str
    required: false

  vdc_id:
    description:
    - Unique identifier of the VDC to retrieve.
    - If specified, returns details of a single VDC matching that ID.
    - Mutually exclusive with I(vdc_name) and I(local_vdc).
    type: str
    required: false

  local_vdc:
    description:
    - When C(true), retrieves only the local VDC details.
    - Mutually exclusive with I(vdc_name) and I(vdc_id).
    type: bool
    required: false

notes:
- The I(check_mode) is supported. This is a read-only info module.
- The objectscale_client Python package must be installed.
  Generate it with C(make build_client) and install with C(make install_client).
- The C(secretKeys) field is omitted from all returned VDC records
  to prevent credential exposure in logs or playbook output.
- When none of I(vdc_name), I(vdc_id), or I(local_vdc) is specified,
  all VDCs in the federation are returned.
- For a single-site deployment, the list will contain one VDC (the local VDC).
'''

EXAMPLES = r'''
- name: List all VDCs in the federation
  dellemc.objectscale.vdc_info:
    objectscale_host: "{{ objectscale_host }}"
    objectscale_username: "{{ objectscale_username }}"
    objectscale_password: "{{ objectscale_password }}"
    validate_certs: false
  register: result

- name: Get local VDC details
  dellemc.objectscale.vdc_info:
    objectscale_host: "{{ objectscale_host }}"
    objectscale_username: "{{ objectscale_username }}"
    objectscale_password: "{{ objectscale_password }}"
    validate_certs: false
    local_vdc: true
  register: result

- name: Get VDC details by name
  dellemc.objectscale.vdc_info:
    objectscale_host: "{{ objectscale_host }}"
    objectscale_username: "{{ objectscale_username }}"
    objectscale_password: "{{ objectscale_password }}"
    validate_certs: false
    vdc_name: "vdc-site-a"
  register: result

- name: Get VDC details by ID
  dellemc.objectscale.vdc_info:
    objectscale_host: "{{ objectscale_host }}"
    objectscale_username: "{{ objectscale_username }}"
    objectscale_password: "{{ objectscale_password }}"
    validate_certs: false
    vdc_id: "urn:storageos:VirtualDataCenterData:abc123"
  register: result
'''

RETURN = r'''
changed:
    description: Whether the resource changed. Always C(false) for info modules.
    returned: always
    type: bool
    sample: false

vdcs:
    description: List of VDC records from the ObjectScale system.
    returned: always
    type: list
    elements: dict
    contains:
        id:
            description: Unique immutable identifier generated by ECS for this VDC.
            type: str
        name:
            description: User-assigned name for this VDC resource.
            type: str
        vdcId:
            description: VDC identifier string used in federation operations.
            type: str
        vdcName:
            description: VDC name string used in federation operations.
            type: str
        local:
            description: Whether this VDC is the local (current site) VDC.
            type: bool
        interVdcEndPoints:
            description: Comma-separated list of inter-VDC communication endpoints.
            type: str
        interVdcCmdEndPoints:
            description: Comma-separated list of inter-VDC command endpoints.
            type: str
        managementEndPoints:
            description: Management endpoints for this VDC.
            type: str
        permanentlyFailed:
            description: Whether this VDC is in a permanently failed state.
            type: bool
        is_encryption_enabled:
            description: Whether encryption is enabled for this VDC.
            type: bool
        creation_time:
            description: Unix timestamp (ms) when this VDC was created in ECS.
            type: int
        inactive:
            description: Whether the VDC is inactive (pending removal).
            type: bool
        remote:
            description: Whether this is a remote (federated) VDC.
            type: bool
        global:
            description: Whether this is a global VDC resource.
            type: bool
        internal:
            description: Whether this is an internal VDC resource.
            type: bool
        hosted:
            description: Whether this VDC is hosted.
            type: bool
'''

from typing import Any, Dict, List, Optional
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.dellemc.objectscale.plugins.module_utils import utils
from ansible_collections.dellemc.objectscale.plugins.module_utils.utils import (
    HAS_OBJECTSCALE_CLIENT,
)

try:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client import api_client as objectscale_api_client
except Exception:
    objectscale_api_client = None

try:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client import _stubs as objectscale_client_stubs
except Exception:
    objectscale_client_stubs = None

try:
    from ansible_collections.dellemc.objectscale.plugins.module_utils.objectscale_client.api.zone_info_api import ZoneInfoApi
except Exception:
    ZoneInfoApi = None  # type: ignore[assignment,misc]

_SENSITIVE_FIELDS = frozenset(['secretKeys', 'secret_keys'])


def _mask_sensitive(vdc_dict: Dict[str, Any]) -> Dict[str, Any]:
    """Remove sensitive fields from a VDC dict to prevent credential leakage."""
    return {k: v for k, v in vdc_dict.items() if k not in _SENSITIVE_FIELDS}


class VdcInfo(object):
    """Class for gathering VDC information from ObjectScale."""

    @staticmethod
    def _ensure_secretstr_compatibility() -> None:
        """Patch generated stubs for runtime compatibility when pydantic is absent."""
        if objectscale_api_client is not None:
            secret_str_cls = getattr(objectscale_api_client, 'SecretStr', None)
            if secret_str_cls is str:
                class _CompatSecretStr(str):
                    def get_secret_value(self) -> str:
                        return str(self)

                objectscale_api_client.SecretStr = _CompatSecretStr

        if objectscale_client_stubs is not None:
            base_model_cls = getattr(objectscale_client_stubs, 'BaseModel', None)
            if base_model_cls is not None and not hasattr(base_model_cls, 'model_dump'):
                def _model_dump(self, *args, **kwargs):  # type: ignore[no-redef]
                    data = getattr(self, '__dict__', None)
                    if isinstance(data, dict):
                        return dict(data)
                    return {}

                base_model_cls.model_dump = _model_dump

    def __init__(self) -> None:
        self.module_params = utils.get_objectscale_management_host_parameters()
        self.module_params.update(dict(
            vdc_name=dict(type='str', required=False),
            vdc_id=dict(type='str', required=False),
            local_vdc=dict(type='bool', required=False),
        ))

        self.module = AnsibleModule(
            argument_spec=self.module_params,
            mutually_exclusive=[('vdc_name', 'vdc_id', 'local_vdc')],
            supports_check_mode=True,
        )

        if not HAS_OBJECTSCALE_CLIENT:
            self.module.fail_json(
                msg="The objectscale_client Python package is required. "
                    "Install it with: pip install pydantic urllib3 python-dateutil"
            )
            return

        if ZoneInfoApi is None:
            self.module.fail_json(
                msg="ObjectScale ZoneInfo API client is unavailable. Rebuild/install objectscale_client."
            )
            return

        try:
            self._ensure_secretstr_compatibility()
            self.api_client = utils.get_objectscale_connection(self.module.params)
            self.zone_info_api = ZoneInfoApi(self.api_client)
        except Exception as e:
            self.module.fail_json(msg="Failed to connect to ObjectScale: %s" % str(e))
            return

    def list_all_vdcs(self) -> List[Dict[str, Any]]:
        """List all VDCs configured in the federation."""
        try:
            response = self.zone_info_api.zone_info_service_list_all_vdc()
            result = response.to_dict() if hasattr(response, 'to_dict') else {}
            vdc_list = result.get('vdc') or []
            return [_mask_sensitive(v) if isinstance(v, dict) else _mask_sensitive(
                v.to_dict() if hasattr(v, 'to_dict') else {}
            ) for v in vdc_list]
        except Exception as e:
            error_msg = utils.determine_error(e)
            self.module.fail_json(msg="Listing all VDCs failed with error: %s" % error_msg)
            return []

    def get_local_vdc(self) -> Optional[Dict[str, Any]]:
        """Get the local VDC details."""
        try:
            response = self.zone_info_api.zone_info_service_get_local_vdc()
            vdc = response.to_dict() if hasattr(response, 'to_dict') else {}
            return _mask_sensitive(vdc) if vdc else None
        except Exception as e:
            error_msg = utils.determine_error(e)
            self.module.fail_json(msg="Getting local VDC failed with error: %s" % error_msg)
            return None

    def get_vdc_by_name(self, vdc_name: str) -> Optional[Dict[str, Any]]:
        """Get VDC details by name."""
        try:
            response = self.zone_info_api.zone_info_service_get_vdc_by_name(vdc_name=vdc_name)
            vdc = response.to_dict() if hasattr(response, 'to_dict') else {}
            return _mask_sensitive(vdc) if vdc else None
        except Exception as e:
            status = getattr(e, 'status', None)
            if str(status) in ('404', '400'):
                return None
            error_msg = utils.determine_error(e)
            self.module.fail_json(
                msg="Getting VDC '%s' by name failed with error: %s" % (vdc_name, error_msg)
            )
            return None

    def get_vdc_by_id(self, vdc_id: str) -> Optional[Dict[str, Any]]:
        """Get VDC details by ID."""
        try:
            response = self.zone_info_api.zone_info_service_get_vdc_by_id(vdc_id=vdc_id)
            vdc = response.to_dict() if hasattr(response, 'to_dict') else {}
            return _mask_sensitive(vdc) if vdc else None
        except Exception as e:
            status = getattr(e, 'status', None)
            if str(status) in ('404', '400'):
                return None
            error_msg = utils.determine_error(e)
            self.module.fail_json(
                msg="Getting VDC with ID '%s' failed with error: %s" % (vdc_id, error_msg)
            )
            return None

    def perform_module_operation(self) -> None:
        """Determine the query type and return VDC information."""
        vdc_name = self.module.params.get('vdc_name')
        vdc_id = self.module.params.get('vdc_id')
        local_vdc = self.module.params.get('local_vdc')

        if vdc_name:
            vdc = self.get_vdc_by_name(vdc_name)
            vdcs = [vdc] if vdc else []
        elif vdc_id:
            vdc = self.get_vdc_by_id(vdc_id)
            vdcs = [vdc] if vdc else []
        elif local_vdc:
            vdc = self.get_local_vdc()
            vdcs = [vdc] if vdc else []
        else:
            vdcs = self.list_all_vdcs()

        self.module.exit_json(changed=False, vdcs=vdcs)


def main() -> None:
    """Create VdcInfo object and perform module operation."""
    obj = VdcInfo()
    obj.perform_module_operation()


if __name__ == '__main__':
    main()
